### ISSUE TITLE
Error when trying to use in windows. Cannot open file in C:/Users/<username>/AppData/Local/Temp/VIoD98D.tmp?

### ISSUE THREAD

**Issue by chaitanyagurrapu** [mbbill/undotree#109]
Hi,
I have installed the plugin on a windows 10 machine.
When I try to use it, I get the following error ... 
Error detected while processing function <SNR>60_undotreeAction[6] ...
Cannot open file in C:/Users/<username>/AppData/Local/Temp/VIoD98D.tmp

This can seen in the screenshot below

![Screenshot](https://user-images.githubusercontent.com/853059/66725286-b6fa0880-ee73-11e9-82d6-1741a78712a6.png)

I have updated my vimrc and gvim rc to set the undodir variable as follows ...

```
:set backupdir=.backup/,~/.backup/,/tmp//
:set directory=.swp/,~/.swp/,/tmp//
:set undodir=.undo/,~/.undo/,/tmp//
```

As you can see in the below screenshots, the .swp directory seems to be used, but the .undo directory doesn't seem to be used.

![Screenshot_2](https://user-images.githubusercontent.com/853059/66725454-9cc12a00-ee75-11e9-994a-511bdf50b302.png)

![Screenshot_3](https://user-images.githubusercontent.com/853059/66725451-8fa43b00-ee75-11e9-8115-5c181878ebad.png)

**Comment by mbbill** [comment]
seems like a permission issue.
does it work without below sections ?
```
:set backupdir=.backup/,~/.backup/,/tmp//
:set directory=.swp/,~/.swp/,/tmp//
:set undodir=.undo/,~/.undo/,/tmp//
```

**Comment by chaitanyagurrapu** [comment]
No, it doesn't. I added those to try and resolve the issue in the first place. This issue [here](https://github.com/mbbill/undotree/issues/58) seemed the closest. I googled for how to set up backup and undo directories in vim and added those sections.

**Comment by mbbill** [comment]
can you try on a fresh vim install?

**Comment by chaitanyagurrapu** [comment]
Hmm ... fresh install seems to have fixed the issue. I even removed the custom sections above

**Comment by mgdreamingstar** [comment]
I have this issue these days on Win 10.
setting: `set backupdir=$CONFIG_DIR.'\tmp\undo'`
then vim shows error: cannot open file in C:\Users\<username>\.config\tmp\undoD%%Documents%test.txt

however, maybe vim adds the file's name to the backupdir path.
