### ISSUE TITLE
Why I `:UndotreeShow` will get this error?

### ISSUE THREAD

**Issue by Freed-Wu** [mbbill/undotree#110]
```
|| Error detected while processing function
|| undotree#UndotreeShow[3]
|| undotree#UndotreeToggle[11]
|| 62[13]
|| 64[55]
|| 60[5]
|| 75[73]
|| W10: Warning: Changing a readonly file
```

the warning appear in `function! s:diffpanel.Update(seq,targetBufnr,targetid) abort`
```
    setlocal modifiable
    call s:exec('1,$ d _')
```

Perhaps it should `:setlocal noreadonly`? But I `:au filetype undotree setlocal noreadonly` cannot work. in `function! Undotree_CustomMap()` add `setlocal noreadonly` cannot work, too.

OS: Windows 10
vim: gvim8.1

Thank you!

**Comment by mbbill** [comment]
would you mind try again with a clean VIM installation? no other plugins and default vim config. that way it would be easy for me to repro locally.

**Comment by Freed-Wu** [comment]
You are right!
my vimrc has `autocmd Filetype diff set modifiable` make this fault.
I am sorry!
Thank you!
