### ISSUE TITLE
Why loaded the undo history file  could spend so much time? 

### ISSUE THREAD

**Issue by applejwjcat** [mbbill/undotree#120]
When I use vim to open file, I got the starttime  file:
809.836  690.122  690.122: sourcing /Users/Tristan/.config/nvim/modules/undotree.vim
811.747  000.216  000.216: sourcing /Users/tristan/.config/nvim/plugged/undotree/plugin/undotree.vim
This is my undotree.vim config : 
silent !mkdir -p $HOME/.config/nvim/generate/undotreetmp/backup
silent !mkdir -p $HOME/.config/nvim/generate/undotreetmp/undo
"silent !mkdir -p $HOME/.config/nvim/generate/undotreetmp/sessions
set backupdir=$HOME/.config/nvim/generate/undotreetmp/backup,.
set directory=$HOME/.config/nvim/generate/undotreetmp/backup,.
if has('persistent_undo')
    set undofile
    set undodir=$HOME/.config/nvim/generate/undotreetmp/undo,.
endif

" let g:undotree_debugenable = 0
" let g:undotree_debugfile = $HOME.'/.config/nvim/generate/undotreetmp/undotree.log'
let g:undotree_DiffAutoOpen = 1
let g:undotree_SetFocusWhenToggle = 1
let g:undotree_ShortIndicators = 1
let g:undotree_WindowLayout = 2
let g:undotree_DiffpanelHeight = 8
let g:undotree_SplitWidth = 24
function g:Undotree_CustomMap()
	nmap <buffer> n <plug>UndotreeNextState
	nmap <buffer> p <plug>UndotreePreviousState
	nmap <buffer> N 5<plug>UndotreeNextState
	nmap <buffer> P 5<plug>UndotreePreviousState
endfunc
I guess the configuration let vim to load the undodir file. So it wasted so much time. 
Is there any choice to avoid the problems and improve the start speed?

**Comment by mbbill** [comment]
You can comment out
```
set undofile
set undodir=$HOME/.config/nvim/generate/undotreetmp/undo,.
```
To see if it's faster. If yes then there's nothing we can do in undotree since it's just vim loading the undofile.

**Comment by applejwjcat** [comment]
No, I  commented out the lines:
"silent !mkdir -p $HOME/.config/nvim/generate/undotreetmp/sessions
" set backupdir=$HOME/.config/nvim/generate/undotreetmp/backup,.
" set directory=$HOME/.config/nvim/generate/undotreetmp/backup,.
" if has('persistent_undo')
    " set undofile
    " set undodir=$HOME/.config/nvim/generate/undotreetmp/undo,.
" endif
but it doesn't make sense. The output is :
814.035  690.973  690.973: sourcing /Users/Tristan/.config/nvim/modules/undotree.vim

Is there some wrong?

**Comment by applejwjcat** [comment]
I got it!
Just comment out the line:
silent !mkdir -p $HOME/.config/nvim/generate/undotreetmp/backup
silent !mkdir -p $HOME/.config/nvim/generate/undotreetmp/undo
maybe because these directories is generated, and there are a lot of files in them. So when the system want to generate again, they should be moved again! The time is just wasted by the system operations !!

**Comment by mbbill** [comment]
Good to know it's fixed!
