### ISSUE TITLE
Feature: show diff without hitting CR

### ISSUE THREAD

**Issue by kaldown** [mbbill/undotree#122]
Would be useful to show interactive changes while moving through the tree.
And when accommodated - hit "accept".

Rather than hit "enter" every time you move across the history.

**Comment by mbbill** [comment]
you may use `J` and `K` to move through the tree

**Comment by kaldown** [comment]
Yes, but in order to see what will happen, I have to hit ENTER

**Comment by mbbill** [comment]
no you don't. It's the capital 'J' & 'K'. i.e. <shift> + j/k

**Comment by kaldown** [comment]
That's exactly what I am looking for. Thanks.
