### ISSUE TITLE
E824: Incompatible undo file

### ISSUE THREAD

**Issue by kaldown** [mbbill/undotree#125]
Strange error. Using neovim-nightly.
`E824: Incompatible undo file: /home/kaldown/.local/share/nvim/undo/%home%kaldown%projects%campus%models%mentor.py`

with vimrc: https://github.com/kaldown/dotfiles/blob/master/.config/nvim/plug_config/base.vim#L134

**Comment by mbbill** [comment]
if it only happens on the `mentor.py` I guess it's probably because this file was changed by some other editors and lost sync with its persistent undo file.

**Comment by kaldown** [comment]
In multiple files (but not all, can't find a pattern)
And I use one `vim` for everything ;)

**Comment by blankname** [comment]
Neovim recently [changed](https://github.com/neovim/neovim/pull/13973#issuecomment-789544740) their undo format.

See also the 2021/3/3 entry to the "[Following HEAD](https://github.com/neovim/neovim/issues/14090)" thread.

**Comment by mbbill** [comment]
so I guess the undo files that doesn't work are probably left-off before this update?

**Comment by kaldown** [comment]
> so I guess the undo files that doesn't work are probably left-off before this update?

I just recently started using `undotree`, there is nothing in `~/.undodir`

**Comment by blankname** [comment]
@kaldown,

This has nothing to do with undo tree.
According the the error message you posted your undo files are in `/home/kaldown/.local/share/nvim/undo/`.

> E824: Incompatible undo file: home/kaldown/.local/share/nvim/undo/%home%kaldown%projects%campus%models%mentor.py

**Comment by kaldown** [comment]
True.
clearing this folder solves an issue.
I wasn't paying enough attention.

Thank you
