### ISSUE TITLE
how to recover file from undotree backup

### ISSUE THREAD

**Issue by codingbeasts** [mbbill/undotree#138]
recently my hard drive got corrupted and all data has been lost.
so what i found that i use vim with undotree so all my backup files has been stored in .vim/undotree directory.

so i need to recover all those files from there.
please tell me how to do it.

**Comment by mbbill** [comment]
I’m sorry to hear that! Unfortunately AFAIK the undo history only stores a fraction of the original content, mainly the changed parts, so it can’t be used to restore data without the original file.

**Comment by codingbeasts** [comment]
thanks
