### ISSUE TITLE
Out of the box theme makes text unreadable

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mbbill/undotree#153]
![2023-apr-19--22-31-01_maim](https://user-images.githubusercontent.com/3514015/233167769-60c1b4a2-b651-4ebe-b028-d1df83b44a9d.png)

As I understand, out of the box you are focusing on the white theme?

**Comment by mbbill** [comment]
no. it's mapped to `DiffAdd` `DiffChange` and `DiffDelete`. See https://github.com/mbbill/undotree/blob/master/plugin/undotree.vim#L153

How it looks depends on your colorscheme.
