### ISSUE TITLE
Is it possible to save undo files only when inside a project?

### ISSUE THREAD

**Issue by jtw023** [mbbill/undotree#157]
I have persistent undo set to where every file I open in vim automatically saves its history to a specified directory. This in itself is amazing and I can just manually delete undo files after I finish a project or something like that. In the interest of making it better though, is there a way to only save undo history for a certain project?

For example, if I'm in a certain directory then make the undo history persistent, otherwise delete it after each session. I suppose I could just set a {"BufLeave", "BufWinLeave"} autocommand to delete the undo file based on file type.

<details>
    <summary>Config File:</summary>

```
vim.g.undotree_SetFocusWhenToggle = 1
vim.g.undotree_TreeNodeShape = ' '
vim.g.undotree_TreeVertShape = ' 󰁝 '
vim.g.undotree_TreeSplitShape = '󰁜 '
vim.g.undotree_TreeReturnShape = '  󰁛 '
vim.g.undotree_SplitWidth = 40

-- Add Persistent Undo
vim.cmd[[
" guard for distributions lacking the 'persistent_undo' feature.
if has('persistent_undo')
    " define a path to store persistent undo files.
    let target_path = expand('<redacted>')
    " create the directory and any parent directories
    " if the location does not exist.
    if !isdirectory(target_path)
        call system('mkdir -p ' . target_path)
    endif
    " point Vim to the defined undo directory.
    let &undodir = target_path
    " finally, enable undo persistence.
    set undofile
endif
]]
```
</details>

**Comment by jtw023** [comment]
Would love something that says `if filetype not in ("python", "sql") then delete`. Couldn't make that work though so for now I'm just going with an autocommand that runs on buffer leave for certain filetypes.
```
vim.api.nvim_create_autocmd({"BufLeave", "BufWinLeave"}, {
	pattern = { "*.lua", "*.vim", "*.md", "*.sqlfluff", "*.*sh*", "*git*", "*config*" },
	command = [[ :call delete(undofile(@%)) ]],
	group = group2
})
```

**Comment by mbbill** [comment]
maybe just try turning off the persistent undo in the BufEnter for certain files?

**Comment by jtw023** [comment]
For anyone else who may come looking, I have `vim.opt.undofile = false` in an nvim options file and then use an autocommand to turn it on only for a certain directory.

Here's the autocommand I use just for SQL files:
```
vim.api.nvim_create_autocmd({"BufRead", "BufEnter", "BufWinEnter"}, {
    pattern = "/absolute/path/to/directory/*.sql",
    command = [[ :set undofile ]],
    group = nvimOptions
})
```

And here's the autocommand I use for all files:
```
vim.api.nvim_create_autocmd({"BufRead", "BufEnter", "BufWinEnter"}, {
    pattern = "*/relative/path/to/directory/*",
    command = [[ :set undofile ]],
    group = nvimOptions
})
```
