### ISSUE TITLE
Adding a FOSS license

### ISSUE THREAD

**Issue by ColinKennedy** [mbbill/undotree#169]
Hi, I love and use this plug-in. It's one of perfect, situational "when you need it, you need it" plug-ins that I can't imagine myself without! My workplace is cautious about allowing code without a `LICENSE` file and it'd be a big help if this plug-in could use a FOSS license. I'm sure others in the same position and would appreciate it too. Could a FOSS license please be added if this plug-in is meant for public use?

**Comment by mbbill** [comment]
done.

**Comment by ColinKennedy** [comment]
Thank you!
