### ISSUE TITLE
Please bring back a Changelog

### ISSUE THREAD

**Issue by adamency** [mbbill/undotree#172]
I've read the changelog in doc.txt whose last entry goes back to 2017 and which states that no updates will be recorded there anymore and to refer to the github project for information.

However, on github, the only way to get a changelog is with the **Releases** page whose last release was in 2019 but even so, absolutely no release changelog provided any information about added features and fixes.

So my understanding is that there is absolutely no changelog anymore since 2017, which means 6 years of updates that cannot be known except when reading the actual commits made on the git repo.

I want to point out that git commit history is **not** a changelog, it is simply the code history of the project but is meant for developers and not users. A random user could understand the evolution of your project in seconds with the changelog, now it takes dozens of minutes of research in the git history to understand what has been going on in the past 6 years.

I don't understand why you stopped making a changelog. Please bring it back, it would help a lot of your users in understanding the project/plugin.

**Comment by mbbill** [comment]
If you find it useful how about a PR?

**Comment by adamency** [comment]
@mbbill How can I make a PR of a changelog when I'm precisely looking for what were the changes these past 6 years ?

**Comment by mbbill** [comment]
So you want other people to do it for you? I don’t think this project owes anyone anything, if you want something stop complaining and help improve it.

**Comment by adamency** [comment]
God you're unhinged.

1) I didn't complain but simply made a request as is perfectly standard on github. Then I made perfectly due research by looking everywhere in your documentation, release notes, github project, etc... before making such an issue and then detailed all of my research in here.

2) Making a changelog as a the software primary dev takes max minutes. For me to do it, as a completely new user of your software, it would take reading and understanding your entire code base to know all the features, then look at a full diff from the state 6 years ago and check which one was already there and which not, and what was only fixed, etc... Which would multiple entire days of work.

If you can't understand how unreasonable and outright delusional, but mostly extremely rude, you are with your request, I don't have to waste time anymore in here.

You are absolutely shooting yourself in the foot with your behavior and clearly not deserving of any help. I have dozens of other projects where maintainers are much nicer and diplomatic on which I want to devote my time far before yours. Bye.

**Comment by mbbill** [comment]
Can’t tell if it’s github or reddit, may kids go everywhere nowadays gosh

**Comment by mbbill** [comment]
bye.
