### ISSUE TITLE
My $HOME directory is filled with undo files

### ISSUE THREAD

**Issue by Agent-E11** [mbbill/undotree#173]
and I think that undotree is the culprit.

My `$HOME` directory is filled with files, with filenames in this format:

```
%path%to%file.md
%path%to%other%file%over%here.html
%home%agente11%project%.git%COMMIT_EDITMSG
%home%agente11%my_file.md
```

When I `cat` the files, they are mostly garbage data, but with snippets of text (this file is `/home/agente11/.gitconfig`):

```
Vim�UnDo��Ԝr�ڻ^����
                   �q
                     Ϗ�$^!0U&���/B��e��_�����e���       editor = sensible-editor5��C⸮5��
```

Does anyone know why these files are being created, and how I can stop it?

**Comment by Agent-E11** [comment]
I have tried to change the `g:undotree_UndoDir` variable, but I don't think it has worked (I am using Neovim):
```lua
-- In a lazy.nvim plugin definition file
return {
    "mbbill/undotree",
    config = function () -- This function runs when undotree is loaded
        vim.g.undotree_UndoDir = "~/.undoDir/" -- Set variable
        vim.keymap.set("n", "<leader>u", vim.cmd.UndotreeToggle)
    end
}
```

I have also tried setting the variable directly in command mode:

```vim
:let g:undotree_UndoDir = "~/.undoDir"
```

Neither of these did anything (that I can tell), the directory `~/.undoDir` stayed empty

**Comment by Agent-E11** [comment]
I also discovered there is a directory called `~/.vim/undotree`, and it has files named the same way (not the same files though)

**Comment by mbbill** [comment]
does the issue go away if you disable the plugin?

**Comment by Agent-E11** [comment]
@mbbill I moved the plugin from `plugins/undotree.lua` to `disabled_plugins/undotree.lua` (I was not able to run `:UndoTreeToggle` so it is definitely disabled) and it did not fix the issue. So, it is probably not undotree then...

If it isn't an issue with undotree, do you have any idea of what else it could be?

**Comment by mbbill** [comment]
then you might want to report the issue to https://github.com/jiaoshijie/undotree

**Comment by Agent-E11** [comment]
> then you might want to report the issue to https://github.com/jiaoshijie/undotree

I don't think it could be that, because I don't think I have that plugin installed...
Anyway, thanks for helping me rule out this plugin

**Comment by mbbill** [comment]
In case you still don’t get it, the plugin isn’t written in lua

**Comment by Agent-E11** [comment]
I have figured out the issue. It was not a problem with this plugin.

What I did was, I set the undodir wrong:

```lua
vim.opt.undodir = os.getenv("HOME") or os.getenv("UserProfile") .. "/.vim/undodir"
```

So it was either `$HOME` on Linux systems, or `$UserProfile/.vim/undodir` on Windows systems 🤦‍♂️

I added parentheses and now it works
```lua
vim.opt.undodir = (os.getenv("HOME") or os.getenv("UserProfile")) .. "/.vim/undodir"
```
