### ISSUE TITLE
Any reasons for using eventignore?

### ISSUE THREAD

**Issue by siduck** [mbbill/undotree#174]
Hi there,since this plugin ignores events , one of its unlisted buffers get added to my bufferline plugin and my check for including listed buffers doesnt work.
 https://github.com/search?q=repo%3Ambbill%2Fundotree+eventignore&type=code

**Comment by mbbill** [comment]
The Undo-Tree plugin ignores events in its panels because those panels are mainly for showing info, not for editing like other windows. Since we often switch between these panels with hotkeys, ignoring events helps avoid triggering stuff by accident.

**Comment by siduck** [comment]
How would bufferline plugins exclude it :thinking:
