### ISSUE TITLE
Restore changes to new file from persistent undotree file

### ISSUE THREAD

**Issue by ngopalas** [mbbill/undotree#176]
I have a persistent undotree file in my .undodir directory. However, due to a version control issue I lost all my changes. I do have the original file, or a file very similar to the original file. Currently when I restored the original file, and I open up Undotree, the undotree is empty. How can I use undotree to recover my lost changes?

**Comment by mbbill** [comment]
this happens fairly often, and afaik it's not possible to recover with the undofiles once vim believed the file is different from the original.
As stated in the vim help:
```
"File contents changed, cannot use undo info"
	The file text differs from when the undo file was written.  This means
	the undo file cannot be used, it would corrupt the text.  This also
	happens when 'encoding' differs from when the undo file was written.
```

**Comment by ngopalas** [comment]
Ok thank you, I was able to recover some of the code text changes with the "strings <undodirfile>" command. Thank you for responding, and creating this plugin!

**Comment by ngopalas** [comment]
In the above I meant "strings .undodir/%filename" command.
