### ISSUE TITLE
UndotreeToggle  is failing with "diff" is not executable.

### ISSUE THREAD

**Issue by luislopes-outsystems** [mbbill/undotree#183]
Hi, not sure what happened. 
Everything was working in the past. 
Tried to use recently and started having this error:

Error detected while processing function undotree#UndotreeToggle[19]..function undotree#UndotreeToggle[11]..<SNR>33_new[2]..41:                                                                                                                 line   10:  

Can't use this plugin.

I'm on a windows machine. not sure if that affects or not the issue. but on windows diff is not an executable

**Comment by b0ae989c** [comment]
This is expected. See https://github.com/mbbill/undotree/blob/56c684a805fe948936cda0d1b19505b84ad7e065/doc/undotree.txt#L346-L350

**Comment by franck-noahk** [comment]
I have also run into this. It was working a few months ago and has recently stopped. Maybe something to do with windows updates?
Running 'diff' from the command line seems to provide a normal looking output. 

Did you figure out what to do to resolve this?

![image](https://github.com/user-attachments/assets/41da9e13-fe45-4e00-aefb-6bcba9ac49bc)

**Comment by luislopes-outsystems** [comment]
in my case. when I reinstalled git , I messed up with PATHs. and on my system diff tool is on  C:\Program Files\Git\usr\bin\diff.exe. 
So I just added that to the path, and everything started working again.

**Comment by porant** [comment]
Same here `Vim(echoerr):"diff" is not executable.`
