### ISSUE TITLE
persistent_undo option is missing

### ISSUE THREAD

**Issue by wikimatze** [mbbill/undotree#23]
Hi,

you mentioned in the README, that it is possible to have persistent undotree but I can not  find the option in the sources. Are you going to implement this feature or is it an error in the documentation?

**Comment by Drachenfels** [comment]
I know this is issue is closed, but I hope it will reach the target. ;-) I would recommend to mention that in a readme file, there is information how to save persistent undo elsewhere, but not that it's built-in function of vim. Noobs like me check for option in undo documentation and will find nothing. A bit confusing. 

Good job!
