### ISSUE TITLE
Please consider splitting off the functions into a separate autoload script.

### ISSUE THREAD

**Issue by inkarkat** [mbbill/undotree#32]
At 39 KB, `plugin/undotree.vim` is certainly one of the larger plugins, and all of that is loaded into Vim during each startup. At least I open the Undotree only occasionally (but when I do, it's such a great help and pleasure!)

Basically, all the `:function`s can be moved to a separate `autoload/undotree.vim`, which is then lazily loaded on first use. Just keep the include guard, configuration defaults, command definitions and `:autocmd` in the plugin script. (The latter needs an inline check for the visibility of the Undotree to avoid autoloading on the first event trigger, and some restructuring, maybe making `self.bufname` a global variable.)

You could either leave the global function stubs (like `UndotreeToggle()`) for backwards compatibility, or move them to the autoload script; after all, this just requires a tiny change in clients. Like with the `:autocmd` above, please ensure that `UndotreeIsVisible()` is kept in the plugin (or alternatively a separate `autoload/undotree/status.vim` script) and does _not_ trigger the autoload script, though!

Most of this split is mechanical; I didn't submit a pull request because I'd like to leave the exact execution to you, and because this change invalidates any other outstanding changes. Please let me know what you think of this, and any questions or concerns!

**Comment by mtglsk** [comment]
Afaik if using vim-plug this issue can be circumvented, ie.

    Plug 'mbbill/undotree', { 'on': 'UndotreeToggle' }

**Comment by lifepillar** [comment]
There has been no progress on this for a long time. But with a recent Vim, I put Undotree under `pack/*/opt`, so that it does not slow down Vim at startup. Then, I define the following mapping:

    nnoremap <silent> <leader>u :<c-u>if !exists("g:loaded_undotree")
          \ <bar>packadd undotree
          \ <bar>endif<cr>
          \ :UndotreeToggle<cr>

A refactoring of Undotree would still be welcome, however.

**Comment by benknoble** [comment]
@mbbill If this issue is still up for grabs, I'd be happy to submit such a refactoring this weekend

**Comment by mbbill** [comment]
Thanks @benknoble , it would be great! and to all: sorry for the huge delay which made me ashamed to post on this thread :(
