### ISSUE TITLE
AutoRevert Feature

### ISSUE THREAD

**Issue by pelodelfuego** [mbbill/undotree#50]
How about an autoRevert Feature, 

It is something like:
```
autocmd!    CursorMoved   <buffer>   :call   s:revert()
```
It would give amore interactive way to use UndoTree.

Tranks a lot for sharing this BTW.

**Comment by mbbill** [comment]
Sorry I can't get it, could you elaborate more?

**Comment by pelodelfuego** [comment]
When you move accross node of the undoTree, you need to press <CR> to restore the buffer to its state, 
I suggest to add an option to automate this, like moving to a node auto revert it. You have it on the UndoTree of emacs and it is quiet handy.

Do you need me to explain more ?

**Comment by mbbill** [comment]
You already have it, use J,K instead of j,k to move.

**Comment by mbbill** [comment]
BTW, use double click instead of single click. and everything is configurable if you don't like the key bindings.

**Comment by pelodelfuego** [comment]
Ok, sorry for non relevant issue then.
Are these command customizable ?
For example j, k for autorevert and J, K for simple move ?

Tnaks a lot for your reactivity
