### ISSUE TITLE
Create undodir if set on initialization

### ISSUE THREAD

**Issue by chilicuil** [mbbill/undotree#53]
If set the `undodir` must be create manually, I think undotree could create it automatically on setup.

**Comment by mbbill** [comment]
:h undodir
	List of directory names for undo files, separated with commas. When writing: The first directory that exists is used.

Automatically creating the undodir may change the behavior of this option, for example someone could set undodir to 'folder_linux,folder_win,folder_mac' to fallback to different undo folders based on the current OS.

**Comment by chilicuil** [comment]
I see, then I'm closing this issue, thanks for the reply =)
