### ISSUE TITLE
Jump to the undotree window

### ISSUE THREAD

**Issue by nobe4** [mbbill/undotree#60]
Hi,

Great work with your plugin 👍 

I wonder if there is an option for jumping directly to the undotree window?

Sometime, I am in the following configuration (`[ ]` is the cursor position):

```
_________________
|       |       |
|       |       |
|   b   |  [a]  |
|       |       |
|_______|_______|
```

Then I trigger `UndotreeToggle`, so the view is now:

```
___________________
|  *  |     |     |
|  *  |     |     |
|  *  |  b  | [a] |
|  a  |     |     |
| ___ |_____|_____|
```

Then I want to move to the Undotree window, so I do `<C-w>h` two times, but when I switch to `b` the undotree update itself into `b` also, so I loose the focus on `a`.

Do you know if there is any way to do this?

Thanks

**Comment by mbbill** [comment]
you may try to set
`g:undotree_SetFocusWhenToggle`
then when you invoke UndotreeToggle, to cursor will jump to the undotree window automatically, then press <tab> will return the cursor to its original place which is '[a]' here.
Btw, if you would like to jump to undotree window manually, try `UndotreeFocus`

**Comment by nobe4** [comment]
Nice, `UndotreeFocus` is perfect!

Thanks
