### ISSUE TITLE
Conflicts with command-line window

### ISSUE THREAD

**Issue by nhap96** [mbbill/undotree#63]
When the undo tree panel is on, I cannot have the command-line window correctly rendered as it flashes some errors and return an empty command-line window with the only line: `- seq: 0 -`
I'm using NVIM 0.1.4 and vimplug.
Thanks.

**Comment by mbbill** [comment]
Could not reproduce the issue with nvim on Windows. Would you please provide more information like OS, other plugins, etc.

**Comment by nhap96** [comment]
The issue persists with this [minimal vimrc](https://gist.github.com/nhap96/95959cc174e1dc0f51e450a005fb80a1) on OS X, with NeoVim 0.1.4 and latest vim-plug. You could first `F5` to toggle undotree and then `q:` to open the command line window. Thank you.

**Comment by mbbill** [comment]
Confirmed. I'll fix it soon.

**Comment by mbbill** [comment]
fixed in 97ef890fea5452c1c4c68f0d864c7969d7aba578

**Comment by nhap96** [comment]
Thank you 👍
