### ISSUE TITLE
Debounce to improve perf?

### ISSUE THREAD

**Issue by wincent** [mbbill/undotree#64]
I switched from Gundo to undotree a while back because:

- No Python dependency.
- More compact display.
- More info in display (saved states, last saved etc).
- More configurable(?), or at least, I think I've been able to configure it to behave pretty much the same as Gundo.
- Undotree is live updated as you edit.

One thing, however, makes it very significantly slower, especially when the diff view is open, and that is the way the file contents are immediately updated whenever you navigate to a new version in undotree (in Gundo, the file contents only get updated when you commit to choosing a version). What do you think of "debouncing" mappings (via a `CursorHold` autocmd) such that if I hold down the `j`, key, for instance, it won't actually update the diff view and edited file until I let go of the button?

Another possibility would be to make an option that skips updating the file contents until you press a key to accept a particular version, basically matching what Gundo does.

Thoughts? I could probably submit a PR for either of both of these ideas, based on your recommendation (disclaimer: haven't even looked at the code yet, so unsure of the complexity).

**Comment by mbbill** [comment]
Thanks for the suggestion, but what I'm not quite clear is that, pressing `j` in undotree window won't trigger either content update or diff panel update, it just move the cursor. It more seems like the  uppercase `J` mapping in your description, and this mapping is not intended to handle long distance move. Normally you just need to move the cursor in any normal way (`j,k, <line>gg, etc.`) and then press Enter.
Hope it solves your problem.

**Comment by wincent** [comment]
Interesting. I'm definitely pressing lowercase j. It's good to know that the behavior I'm seeing it not actually intended; I'll do some investigation when i get back to my computer to see if i can figure out what is going on.

**Comment by wincent** [comment]
Seems I am responsible for this problem: 

https://github.com/wincent/wincent/commit/c605d597f39001ee57a3b1b73acc5729a3b46e38

Silly me. Sorry for the noise. And thanks for the great tool.
