### ISSUE TITLE
persistent history not automatically loaded

### ISSUE THREAD

**Issue by mfiano** [mbbill/undotree#66]
I have global-undo-tree-mode enabled, and if I add:

(add-hook 'find-file-hook #'undo-tree-load-history-hook)

then the history is NOT loaded when I open a file.

However, if I manually call undo-tree-load-history, I then have access to the history loaded from disk. This occurs with emacs -Q and the latest MELPA release.

**Comment by mfiano** [comment]
ignore, wrong repo

**Comment by mbbill** [comment]
Hopefully C-x C-c then $vim may fix this :-)

**Comment by griffinqiu** [comment]
+ 10086

**Comment by griffinqiu** [comment]
@mfiano Come. You should to use Vim. ; )

**Comment by mfiano** [comment]
I dropped vim for the emacs years ago. After all, I'm a lisp developer.

**Comment by aisk** [comment]
@mfiano Hi I have the same problem with you, and solved with this method:

macOS:

```
brew uninstall emacs
brew install vim
```

ubuntu:

```
sudo apt autoremove emacs
sudo apt install vim
```

**Comment by mbbill** [comment]
Okay, enough joking, lock the thread.
