### ISSUE TITLE
undo tree empty with autochdir

### ISSUE THREAD

**Issue by Konfekt** [mbbill/undotree#67]
With `vim-fugitive` installed and
```vim
set autochdir
autocmd BufWinEnter,BufNewFile,BufFilePost *
              \ if !exists('g:SessionLoad') && exists(':Glcd') |
              \   Glcd |
              \ endif
```
the undotree (after `:UndoTreeToggle`) is empty in a vim file. For example, in `~/.vimrc`.

**Comment by mbbill** [comment]
duplicated with https://github.com/mbbill/undotree/issues/88
