### ISSUE TITLE
How to use syntax?

### ISSUE THREAD

**Issue by felleg** [mbbill/undotree#68]
Sorry if this is stupid, I tried to install the syntax file so that my document looks like the picture, but it doesn't seem to work. My undotree is white. Is this normal? Where did I fail?

**Comment by justinmk** [comment]
@felleg That's a configuration problem with vim. Could be that your TERM is wrong, or `t_Co` option is wrong, or many other things. https://vi.stackexchange.com is a good place for such questions.

**Comment by mbbill** [comment]
@felleg It's not stupid at all. The syntax of undotree window is linked to pre-defined syntax names, for example the 'UndotreeSeq' is linked to 'Comment' so that the syntax normally fits in different colorschemes quite well.
You may first try to find out if these pre-defined syntax works.

**Comment by felleg** [comment]
What I'm doing so far, I have undotree.vim in my ~/.vim/plugin folder (I sourced it from within vim, so when I do :UndotreeToggle, it opens the undotree). I have the undotree syntax in ~/.vim/plugin/syntax/undotree.vim.

If I have the undotree opened up, and I source the undotree syntax, it seems like it slightly alters the colors of the document in vim, but the colors of the undotree itself stay unchanged.

The TERM value I am using is xterm-256color. Hope this will help you help me! :)

**Comment by mbbill** [comment]
no, you don't need to source either the plugin or the syntax. As long as the entire plugin folder is in your .vim, everything should work out just fine. If not, check you vimrc to find out where's the problem.

**Comment by felleg** [comment]
Ah! I found why, it's because the syntax file was in the ~/.vim/plugin folder, instead of being in ~/.vim/syntax. I moved files around and it now works perfectly. Thanks for your patience!
