### ISSUE TITLE
Error on open

### ISSUE THREAD

**Issue by alex-shamshurin** [mbbill/undotree#74]
Error detetcted while processing function UndotreeToggle <SN>109_new[2]..321

![undotree_14](https://user-images.githubusercontent.com/1595209/29978391-ba6e8742-8f49-11e7-82a0-597389e361b8.jpg)

**Comment by mbbill** [comment]
Hi Alex, Thanks for the feedback. Could you please check if the diff.exe under you vim distribution is executable?

**Comment by alex-shamshurin** [comment]
I'm running on Windows. No, there is no `diff` in shell

**Comment by mbbill** [comment]
official vim distribution has diff.exe bundled, so you should be able to find it in your installation folder.

**Comment by alex-shamshurin** [comment]
No, there were no diff.exe in vim folder. (Gvim 8.0), but  I have added c:\program files\git\usr\bin to system path and this helped.
