### ISSUE TITLE
Include a modeline in documentation

### ISSUE THREAD

**Issue by benknoble** [mbbill/undotree#78]
It's rather common for vim plugins to have a modeline in the documentation file `doc/whatever.txt` like this:

```vim
 vim:tw=78:ts=8:ft=help:norl:
```

This helps doc editors edit the .txt file as though it were vim doc, and not a plain text file with symbols strewn about. 

It's a quick fix and I'd be happy to add it

**Comment by mbbill** [comment]
That's a great suggestion! I'd be happy to merge if you submit the pr :)
