### ISSUE TITLE
undotree-like jumplist panel

### ISSUE THREAD

**Issue by Piping** [mbbill/undotree#84]
Hi,

Is it possible to make a plugin for the jumplist manipulation that works like the undotree?

Thanks for this awesome plugin! Extremely useful when I need it !

**Comment by mbbill** [comment]
hey Piping, sorry for the late reply, i was on vacation last week.
this is a really good idea! However, as far as I know, vim doesn't have an API to expose the internal jump list as a tree. Not sure if there is any workaround for that but I'll keep an eye on it.
