### ISSUE TITLE
autoload/ implementation is incomplete/invalid

### ISSUE THREAD

**Issue by justinmk** [mbbill/undotree#85]
The effort in https://github.com/mbbill/undotree/pull/77 is appreciated, but it is incomplete. 

UndoTree [triggers autoload](https://github.com/mbbill/undotree/blob/f55e50545c10a05e600c068e94dd5bbeb66ccf6f/plugin/undotree.vim#L152) immediately on `BufEnter`, `CursorMoved`, etc. Those events are guaranteed to happen as soon as vim starts.

A possible solution would be to define `augroup Undotree` only when `undotree#UndotreeToggle()` (et al.) are called.

**Comment by mbbill** [comment]
Oh I didn't realize that until you mentioned it. genius!
Thanks for the great suggestion!

**Comment by mbbill** [comment]
Fixed in ee3ff8cc026b8c7a0bb3e56bd9e990830a862005
