### ISSUE TITLE
Marking diffs with signs

### ISSUE THREAD

**Issue by Rich-YoYo** [mbbill/undotree#90]
I thought it might be nice to mark diffs with signs instead of/as well as highlighting the changed lines. In case you're interested, I have attached a diff to add this. It seems to work quite well

regards,

Rich
[undotree_add_diff_signs.txt](https://github.com/mbbill/undotree/files/2339332/undotree_add_diff_signs.txt)

**Comment by mbbill** [comment]
cool! could you please send a pull request? I'm a bit hesitate to pull your code and commit with my name :)

**Comment by Rich-YoYo** [comment]
I'm not precious about it - do what you like with it

If you really prefer though, I'll do it via git. 

So all I have to do now is install git and learn how to use it!!

regards
Rich

**Comment by mbbill** [comment]
never mind, i’ll take care of it.

**Comment by mbbill** [comment]
committed at 364c73dae83bbaa552fa901dbcb082be22f846f4

**Comment by Rich-YoYo** [comment]
Ooops! There is a bug in the patch which can cause signs to be left hanging about when difftree is closed.

In the function, s:diffpanel.CleanUpHighlight(), a call to 'SetTargetFocus()' is required to ensure correct removal of the signs. ie...

call t:undotree:SetTargetFocus()     <--- add this
if (exists("w:undotree_diffsigns"))
  while ....
  ...etc...

I don't know if this call to SetTargetFocus() will cause problems elsewhere but I haven't seen any so far

**Comment by Rich-YoYo** [comment]
By the way, I DID try and do the GIT thing but it all went a bit wrong! :-(

**Comment by mbbill** [comment]
no worries.

Rather than calling into CleanUpHighlight, I'm thinking of a different fix, Could you please check out this pull request https://github.com/mbbill/undotree/pull/91 to see if it works?

Thanks!
