### ISSUE TITLE
E121 and E15 error

### ISSUE THREAD

**Issue by ChenWeird** [mbbill/undotree#96]
If undotree window didn't close before quit the file, there are two erro E121 and E15.

E121: 未定义的变量： t:undotree
E15:  无效的表达式: t:undotree.GetStatusLine()

How to avoid these errors?

**Comment by ChenWeird** [comment]
GVIM 8.1.1 x86 
Win 10 x64

**_vimrc's plugin**
```
 " Vim-Plug 
" Plugins will be downloaded under the specified directory
call plug#begin()
" Declare the list of plugins.
Plug 'yianwillis/vimcdoc'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'ctrlpvim/ctrlp.vim'
Plug 'easymotion/vim-easymotion'
Plug 'mbbill/undotree'
Plug 'tpope/vim-surround'
Plug 'godlygeek/tabular'
Plug 'plasticboy/vim-markdown'
Plug 'dhruvasagar/vim-table-mode'
Plug 'iamcco/markdown-preview.vim'
Plug 'vimwiki/vimwiki', { 'branch': 'dev' }
Plug 'hotoo/pangu.vim'
Plug 'iamcco/dict.vim'
Plug 'benknoble/vim-auto-origami'
" List ends here. Plugins become visible to Vim after this call.
call plug#end()
```
**repeat:**
1. open gvim
2. `:tabe`
3. `:UndotreeToggle`
4. `:q`
5. red erro E121 and E15 come into view

**Comment by mbbill** [comment]
Do you mean the issue is due to plug-in conflict?

**Comment by ChenWeird** [comment]
I do not know. I'll test later.

**Comment by ChenWeird** [comment]
**Find the plug-in conflict**:  [vim-airline/vim-airline](https://github.com/vim-airline/vim-airline)

**Comment by mbbill** [comment]
interesting. Considering undotree.vim is one of the officially supported plugins of vim-airline, there might be some integration error out there.
Thanks for the report! I'll take a look soon.

**Comment by chrisbra** [comment]
I checked vim-airline, this seems to be caused by mbbill/undotree@f1769c3

**Comment by mbbill** [comment]
emm, interesting, even if I comment out those ```setlocal statusline```, the error message is still there. Seems like it's reported from airline's undotree extension. I've sent out a pr for it
https://github.com/vim-airline/vim-airline/pull/1862

**Comment by mbbill** [comment]
Thank you both for spending time on the issue!
I've been one of the airline users since long time ago. @chrisbra Thank you for your efforts of maintaining the great plug-in!

**Comment by chrisbra** [comment]
thanks!

**Comment by chrisbra** [comment]
I have merged your PR, so this issue can be closed now.

**Comment by ChenWeird** [comment]
Cool, everything is ok! Thanks!
