### ISSUE TITLE
how to Persistent undo under windows 10

### ISSUE THREAD

**Issue by ChenWeird** [mbbill/undotree#97]
This code do not work under windows 10 gvim 8.1.1
```
if has("persistent_undo")
    set undodir=~/.undodir/
    set undofile
endif
```
I want to `s/~/$HOME/`，what should I do?

**Comment by ChenWeird** [comment]
Is this ok?
```
" Keep undo history across sessions by storing it in a file
if has('persistent_undo')
    if !isdirectory($HOME.'\.vimundo')
        call mkdir($HOME.'\.vimundo', "", 0770)
    endif
    let &undodir = $HOME . '\.vimundo'
    set undofile
endif
```

**Comment by mbbill** [comment]
> Is this ok?
> 
> ```
> " Keep undo history across sessions by storing it in a file
> if has('persistent_undo')
>     if !isdirectory($HOME.'\.vimundo')
>         call mkdir($HOME.'\.vimundo', "", 0770)
>     endif
>     let &undodir = $HOME . '\.vimundo'
>     set undofile
> endif
> ```

yeah it should work.
